version: '3.8'

services:

  server1:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    env_file: ./env/server1

  server2:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    env_file: ./env/server2

  server3:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    env_file: ./env/server3 
