version: '3.8'

services:

  server1:
    build:
      context: .
      dockerfile: Dockerfile
    image: room_server
    volumes:
      - ./:/usr/src/app
    network_mode: "host"
    env_file: ./env/server1

  server2:
    build:
      context: .
      dockerfile: Dockerfile
    image: room_server
    volumes:
      - ./:/usr/src/app
    network_mode: "host"
    env_file: ./env/server2

  server3:
    build:
      context: .
      dockerfile: Dockerfile
    # network_mode: "host"
    image: room_server
    volumes:
      - ./:/usr/src/app
    env_file: ./env/server3
