version: '3.8'

services:

  server1:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: room_server
    volumes:
      - ./:/usr/src/app
    # network_mode: "host"
    env_file: ./env/server1
    expose:
      - 3000
    ports:
      - 3000:3000

  server2:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: room_server
    volumes:
      - ./:/usr/src/app
    # network_mode: "host"
    env_file: ./env/server2
    expose:
      - 4000
    ports:
      - 4000:4000

  server3:
    build:
      context: .
      dockerfile: dev.Dockerfile
    # network_mode: "host"
    image: room_server
    volumes:
      - ./:/usr/src/app
    env_file: ./env/server3
    expose:
      - 4003
    ports:
      - 4003:4003


  coordinator:
    build:
      context: ../coordinator
      dockerfile: ../coordinator/Dockerfile
    image: coordinator 
    volumes:
      - ../coordinator/:/usr/src/app
        #env_file: ./env/server3
    expose:
      - 3131
    ports:
      - 3131:3131
