app = "hajis-room-game"

primary-region = "arn"

[build]
  dockerfile = "./room_server/Dockerfile"

[deploy]
  strategy = "immediate"

[env]


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250
