# fly.toml app configuration file generated for room3 on 2023-12-08T15:38:27+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "room3"
primary_region = "arn"

[build]
  image = "veikmaster/room_game_server:latest"

[deploy]
  strategy = "immediate"

[env]
  NAME = "server3"
  OTHER_SERVERS = "[{ \"address\": \"hajis-room-game-withered-dream-842.fly.dev/\", \"id\": \"room1\" }, { \"address\": \"room2.fly.dev\", \"id\": \"room2\" }]"
  PORT = "8080"
  ROOM_ID = "room3"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
